### ISSUE TITLE
[Feature Proposal] Support multiple secret files

### ISSUE THREAD

**Issue by runlevel5** [envato/ejson2env-buildkite-plugin#2]
What if your system mains many ejson secret files? For example one for organisation wide project and one for local project. I would like to propose to enhance the plugin to take a list of secret files. Thoughts? cc @stevehodgkiss

**Comment by stevehodgkiss** [comment]
Would that be possible with multiple plugin definitions?

```
- envato/ejson2env#v0.1.0:
  ejson_file: .buildkite/secrets_1.ejson
  ejson_private_key_env_key: EJSON_PRIVATE_KEY_1
- envato/ejson2env#v0.1.0:
  ejson_file: .buildkite/secrets_2.ejson
  ejson_private_key_env_key: EJSON_PRIVATE_KEY_2
```

**Comment by runlevel5** [comment]
@stevehodgkiss :+1: yes that works too. I think we should mention that capability in the README :). Great thanks for your advice

**Comment by runlevel5** [comment]
@stevehodgkiss What do you think about updating the README so that it includes instructions on how to set `EJSON_PRIVATE_KEY` UNIX environment variable that would be available for build? 

```
## FILE: /etc/buildkite-agent/hooks/environment
#!/bin/bash

# The `environment` hook will run before all other commands, and can be used
# to set up secrets, data, etc. Anything exported in hooks will be available
# to the build script.
#
# For example:
#
# export SECRET_VAR=token

set -e

export EJSON_PRIVATE_KEY="MY SECRET"
```

**Comment by stevehodgkiss** [comment]
Yeah, sure. Alternatively with elastic-ci-stack-for-aws, the secrets bucket `env` object can be used to store the EJSON private keys as env vars per-project.

https://github.com/buildkite/elastic-ci-stack-for-aws#build-secrets
